-- 1. Create the complaints table
CREATE TABLE complaints (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id TEXT UNIQUE NOT NULL,
  name         TEXT NOT NULL,
  mobile       TEXT NOT NULL,
  ward_number  TEXT NOT NULL,
  area         TEXT NOT NULL,
  category     TEXT NOT NULL,
  description  TEXT NOT NULL,
  photo        TEXT DEFAULT '',
  landmark     TEXT DEFAULT '',
  status       TEXT DEFAULT 'Submitted',
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (the backend uses SUPABASE_SERVICE_ROLE_KEY which bypasses RLS)
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------
-- MIGRATION: if the table already exists with the old quoted names,
-- run these ALTER TABLE statements in the Supabase SQL editor:
-- ----------------------------------------------------------------
-- ALTER TABLE complaints RENAME COLUMN "complaintId" TO complaint_id;
-- ALTER TABLE complaints RENAME COLUMN "wardNumber"  TO ward_number;
