-- 1. Create the complaints table
CREATE TABLE complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "complaintId" TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  mobile TEXT NOT NULL,
  "wardNumber" TEXT NOT NULL,
  area TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  photo TEXT DEFAULT '',
  landmark TEXT DEFAULT '',
  status TEXT DEFAULT 'Submitted',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Optional: Set up Row Level Security (RLS) if you are not using Service Role Key on the client.
-- Since our backend uses the SUPABASE_SERVICE_ROLE_KEY (which bypasses RLS), 
-- we don't strictly need RLS policies for the API to work, but it is good practice to enable it to secure the database.
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

-- If you ever decide to expose the Anon Key to the frontend, you could add policies like:
-- CREATE POLICY "Enable insert for authenticated users only" ON complaints FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Enable read access for all users" ON complaints FOR SELECT USING (true);
